sudo: required
services:
        - docker
before_install:
        - docker build -t react-test -f ./client/Dockerfile.dev ./client
script:
        - docker run react-test npm test -- --coverage
after_success:
        - docker build -t react multi-client ./client 
        - docker build -t react multi-nginx ./nginx
        - docker build -t react multi-server ./server
        - docker build -t react multi-worker ./worker
        - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
        - docker push multi-client
        - docker push multi-nginx
        - docker push multi-server
        - docker push multi-worker
 
