sudo: required
services:
  - docker

before_install:
  - docker build -t bdwivedi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bdwivedi/react-test npm test -- --coverage

after_success:
  - docker build -t bdwivedi/multi-client ./client
  - docker build -t bdwivedi/multi-nginx ./nginx
  - docker build -t bdwivedi/multi-server ./server
  - docker build -t bdwivedi/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  # Take those images and push them to docker hub
  - docker push bdwivedi/multi-client
  - docker push bdwivedi/multi-nginx
  - docker push bdwivedi/multi-server
  - docker push bdwivedi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-718880092709
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: $aws_secret_key
